[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:llm-tracker-proxy]
command=python -m gunicorn -c config/proxy.conf.py --error-logfile - --access-logfile - src.proxy:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:llm-tracker-api]
command=python -m gunicorn -c config/api.conf.py --error-logfile - --access-logfile - src.api:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:llm-tracker-otlp]
command=python -m gunicorn -c config/otlp.conf.py --error-logfile - --access-logfile - src.otlp:app
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
